<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NADSUM" failures="1" tests="4" name="twoPointers_Array.Intersection" time="0.019" errors="0" timestamp="2022-10-20T01:41:05 IST" skipped="0">
  <testcase classname="twoPointers_Array.Intersection" name="example4" time="0.001"/>
  <system-out/>
  <testcase classname="twoPointers_Array.Intersection" name="example2" time="0.002">
    <failure message="arrays differ firstly at element [0]; expected value is &lt;9&gt; but was &lt;4&gt;. " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: arrays differ firstly at element [0]; expected value is <9> but was <4>. 
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.assertEquals(Assert.java:312)
at org.testng.Assert.assertEquals(Assert.java:294)
at twoPointers_Array.Intersection.example2(Intersection.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- example2 -->
  <system-out/>
  <testcase classname="twoPointers_Array.Intersection" name="example3" time="0.001"/>
  <system-out/>
  <testcase classname="twoPointers_Array.Intersection" name="example1" time="0.015"/>
  <system-out/>
</testsuite> <!-- twoPointers_Array.Intersection -->
